---
defaults:
  - _self_
  - strategy: fedavg
  - optimizer: momentum

num_rounds: 3
num_clients: 10
lr_scheduling: False
cos_decay: False

batch_size: 64 #32 Federated supervised , 64 Federated SSL #128 me autocast se eval_fn k local_fit 
val_ratio: 0.3
rad_ratio: 0.02
partitioning: 'iid'
alpha: 0.5
balance: True #balanced stratified split
num_classes: 10
subset: True 
# datapath: './data'
load: False
cleaner: True
checkpoint_path: models/
datapath: '/home/stavrosmpoul/codebaseMarch/data'
num_workers: 0

C_fraction: 0.5
num_clients_per_round_fit: 8
num_clients_per_round_eval: ${num_clients_per_round_fit}
seed: 2024
client_resources:
  num_cpus: 6
  num_gpus: 1
var_local_epochs: False
var_min_epochs: 1 
var_max_epochs: 4
local_epochs: 1
warm_up_rounds: 8
pretrained: False
warm_start: False

model:
  #Linear evaluation
  checkpoint: 'models/centr_pretrained_0.015_simsiam_resnet18_Jit0.3_min_scale0.4_classes10_E2.pth'
  #'models/best_model_eval_fedsimsiam_fedsimsiam_iid_balanced_Classes=10_Seed=2024_C=5_fraction0.2_B=128_E=1_R=3.npz'
  #'centr_pretrained_0.015_simsiam_resnet18_Jit0.3_min_scale0.4_classes10_E200.pth'
  # 'models/centr_pretrained_0.012_simsiam_resnet18_classes10_E200.pth'
  # 'models/centr_pretrainedV2_simsiam_resnet18_classes10_E200.pth'
  # 'C:\Users\smpoulio_local\Desktop\PythonProjects\FlowerYtTut\models\centr_pretrained_simsiam_resnet18_classes10_E200.pth'
  #C:\Users\smpoulio_local\Desktop\PythonProjects\FlowerYtTut\models\centr_pretrained_simsiam_resnet18_classes10_E200.pth   <-Gia simsiam xwris self.backbone
  #Backbone
  _target_: model.ResNet18


# hydra:
#   sweep:
#     dir: multirun
#     # subdir: ${hydra.job.override_dirname}/${seed}
#     # subdir: ${hydra.job.override_dirname}/${seed}
#   job:
#     config:
#       override_dirname:
#         exclude_keys:
#           - seed
#           - num_rounds
#         kv_sep: _
#         item_sep: _

