hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - optimizer=momentum
    - strategy=fedavg
    - partitioning=dirichlet,iid
    - num_clients=10,16,32
    - num_classes=4,10,30
  job:
    name: main
    chdir: null
    override_dirname: num_classes=4,10,30,num_clients=10,16,32,optimizer=momentum,partitioning=dirichlet,iid,strategy=fedavg
    id: ???
    num: ???
    config_name: base
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: C:\Users\Stavros\Desktop\PythonProjects\FlowerYtTut
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: C:\Users\Stavros\Desktop\PythonProjects\FlowerYtTut\conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      optimizer: momentum
      strategy: fedavg
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
num_rounds: 3
num_clients: 16
lr_scheduling: false
batch_size: 64
partitioning: iid
alpha: 0.5
balance: true
num_classes: 4
subset: true
datapath: D:/DesktopC/Datasets/data/
num_workers: 1
num_clients_per_round_fit: 8
num_clients_per_round_eval: ${num_clients_per_round_fit}
seed: 2024
client_resources:
  num_cpus: 2
  num_gpus: 0.0
var_local_epochs: false
var_min_epochs: 1
var_max_epochs: 4
local_epochs: 1
model:
  _target_: model.ResNet18
strategy:
  name: fedavg
  strategy:
    _target_: flwr.server.strategy.FedAvg
    _recursive_: false
  client_fn:
    _target_: client.generate_client_fn
    _recursive_: false
exp_name: momentum
optimizer:
  _target_: models.train
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  gmf: 0
  mu: 0
