# @package _global_

exp_name: simsiam

optimizer:
  _target_: models.train
  lr: 0.05 # 0.032 # base_lr na dw ksana gia 0.05 h kati endiameso
  momentum: 0.9
  weight_decay: 1e-4 #1 h 5 gia 0.0001 h 0.0005 
  gmf: 0
  mu: 0
  warmup_epochs: 10
  warmup_lr: 0
  final_lr: 0